In [242]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [243]:
df = pd.read_csv('final_dataset/final_model5.csv')

In [244]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,FEDERAL HILL,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,NEW NORTHWOOD,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT / AGG. ASSAULT
2,2012,12,31,25,WHITE,SOUTHEAST,GRACELAND PARK,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,HOLLINS MARKET,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
4,2012,12,31,25,WHITE,SOUTHEAST,JONESTOWN,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY

In [152]:
df["Race"].unique()

array(['WHITE', 'BLACK_OR_AFRICAN_AMERICAN',
       'AMERICAN_INDIAN_OR_ALASKA_NATIVE', 'ASIAN',
       'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER'], dtype=object)

In [135]:
race = ['BLACK_OR_AFRICAN_AMERICAN', 'WHITE', 'ASIAN', 'AMERICAN_INDIAN_OR_ALASKA_NATIVE', 'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER']

In [136]:
enc = OrdinalEncoder(categories = [race])

In [33]:
enc.fit_transform(df[["Race"]])

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [34]:
df[["Race"]] = enc.fit_transform(df[["Race"]])

In [35]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,1.0,SOUTHERN,FEDERAL HILL,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
1,2012,12,31,34,0.0,NORTHEAST,NEW NORTHWOOD,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT
2,2012,12,31,25,1.0,SOUTHEAST,GRACELAND PARK,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
3,2012,12,31,48,0.0,SOUTHERN,HOLLINS MARKET,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,BURGLARY
4,2012,12,31,25,1.0,SOUTHEAST,JONESTOWN,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY FROM AUTO

In [7]:
df["District"].unique()

array(['SOUTHERN', 'NORTHEAST', 'SOUTHEAST', 'NORTHERN', 'SOUTHWEST',
       'NORTHWEST', 'CENTRAL', 'WESTERN', 'EASTERN', 'SD5'], dtype=object)

In [37]:
district = ['NORTHEAST', 'SOUTHEAST', 'CENTRAL', 'NORTHERN', 'SOUTHERN', 'SOUTHWEST', 'NORTHWEST', 'EASTERN', 'WESTERN', 'SD5']

In [38]:
enc = OrdinalEncoder(categories = [district])

In [39]:
enc.fit_transform(df[["District"]])

array([[4.],
       [0.],
       [1.],
       ...,
       [3.],
       [4.],
       [4.]])

In [40]:
df[["District"]] = enc.fit_transform(df[["District"]])

In [41]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,1.0,4.0,FEDERAL HILL,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
1,2012,12,31,34,0.0,0.0,NEW NORTHWOOD,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT
2,2012,12,31,25,1.0,1.0,GRACELAND PARK,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
3,2012,12,31,48,0.0,4.0,HOLLINS MARKET,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,BURGLARY
4,2012,12,31,25,1.0,1.0,JONESTOWN,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY FROM AUTO

In [245]:
df["Neighborhood"].unique()

array(['FEDERAL HILL', 'NEW NORTHWOOD', 'GRACELAND PARK',
       'HOLLINS MARKET', 'JONESTOWN', 'WAVERLY', 'FRANKFORD',
       'BELAIR-EDISON', 'HUNTING RIDGE', 'PATTERSON PLACE', 'WALTHERSON',
       'ARMISTEAD GARDENS', 'IRVINGTON', 'CENTRAL PARK HEIGHTS',
       'CHERRY HILL', 'GLEN', 'EDNOR GARDENS-LAKESIDE',
       'TOWANDA-GRANTLEY', 'COLDSTREAM HOMESTEAD MONTEBELLO', 'LAKELAND',
       'DOWNTOWN', 'HARLEM PARK', 'ABELL', 'BROOKLYN',
       'MIDDLE BRANCH/REEDBIRD PARKS', 'GLENHAM-BELHAR', 'MONDAWMIN',
       'PERKINS HOMES', 'INNER HARBOR', 'WOODMERE', 'CANTON', 'IDLEWOOD',
       'HAMILTON HILLS', 'SAINT JOSEPHS', 'CENTRAL FOREST PARK',
       'RICHNOR SPRINGS', 'ORANGEVILLE', 'BROADWAY EAST',
       'MOUNT WASHINGTON', 'BREWERS HILL',
       'CARROLL - CAMDEN INDUSTRIAL AREA', 'BRIDGEVIEW/GREENLAWN',
       'MEDFIELD', 'WALBROOK', 'CARROLLTON RIDGE', 'LITTLE ITALY',
       'CHINQUAPIN PARK', 'UPTON', 'GARWYN OAKS', 'LAURAVILLE',
       'FRANKLINTOWN', 'BOLTON HILL', 'SHIPLEY HILL', 'KRESSON',
       'CEDMONT', 'PENROSE/FAYETTE STREET OUTREACH', 'KENILWORTH PARK',
       'FELLS POINT', 'BEREA', 'HAMPDEN', 'WESTFIELD', 'MADISON-EASTEND',
       'MID-TOWN BELVEDERE', 'CURTIS BAY', 'DRUID HEIGHTS', 'OLIVER',
       'MOUNT VERNON', 'DOLFIELD', 'FOREST PARK',
       'WASHINGTON VILLAGE/PIGTOWN', 'CARROLL-SOUTH HILTON',
       'FRANKLIN SQUARE', 'ALLENDALE', 'CLIFTON PARK', 'MIDDLE EAST',
       'OVERLEA', 'CHESWOLDE', 'BURLEITH-LEIGHTON', 'GREENSPRING',
       'ROSEMONT', 'ARLINGTON', 'WOODBOURNE HEIGHTS',
       'EAST BALTIMORE MIDWAY', 'PERRING LOCH', 'MOUNT WINANS',
       'GLEN OAKS', 'KESWICK', 'CROSS COUNTRY', 'CHARLES NORTH',
       'CHARLES VILLAGE', 'GROVE PARK', 'WILSON PARK', 'SETON HILL',
       'GAY STREET', 'ROSEMONT HOMEOWNERS/TENANTS', 'MEDFORD',
       'EASTERWOOD', 'HOWARD PARK', 'BARCLAY', 'PANWAY/BRADDISH AVENUE',
       'MORRELL PARK', 'EDMONDSON VILLAGE', 'HANLON-LONGWOOD',
       'FOUR BY FOUR', 'VIOLETVILLE', 'CYLBURN', 'MADISON PARK', 'MOSHER',
       'YALE HEIGHTS', 'PATTERSON PARK NEIGHBORHOOD',
       'BALTIMORE HIGHLANDS', 'WEST FOREST PARK', 'OLDTOWN', 'WESTGATE',
       'LOCH RAVEN', 'FAIRFIELD AREA', 'ORIGINAL NORTHWOOD', 'WEST HILLS',
       'REMINGTON', 'BEVERLY HILLS', 'CONCERNED CITIZENS OF FOREST PARK',
       'POPPLETON', 'ROGNEL HEIGHTS', 'SANDTOWN-WINCHESTER', 'HILLEN',
       'NORTH HARFORD ROAD', 'PENN NORTH', 'FALLSTAFF', 'WINSTON-GOVANS',
       'MONTEBELLO', 'MID-GOVANS', 'HOES HEIGHTS', "RIDGELY'S DELIGHT",
       'SHARP-LEADENHALL', 'ASHBURTON', 'MILTON-MONTFORD',
       'RADNOR-WINSTON', 'NORTHWEST COMMUNITY ACTION', 'SOUTH BALTIMORE',
       'CARE', 'UPPER FELLS POINT', 'WASHINGTON HILL',
       'SETON BUSINESS PARK', 'HARWOOD', 'RESERVOIR HILL',
       'MCELDERRY PARK', 'PARK CIRCLE', 'PEN LUCY', 'HOMELAND',
       'ELLWOOD PARK/MONUMENT', 'PARKLANE', 'UNION SQUARE', 'DORCHESTER',
       'VILLAGES OF HOMELAND', 'FRANKLINTOWN ROAD', 'TUSCANY-CANTERBURY',
       'BELVEDERE', 'LANGSTON HUGHES', 'BAYVIEW', 'BEECHFIELD',
       'JONES FALLS AREA', 'MIDTOWN-EDMONDSON', 'WESTPORT',
       'REISTERSTOWN STATION', 'NORTH ROLAND PARK/POPLAR HILL',
       'DUNBAR-BROADWAY', 'HOPKINS BAYVIEW', 'ARCADIA',
       'PARKVIEW/WOODBROOK', 'ORCHARD RIDGE', 'CEDONIA', 'TEN HILLS',
       'PULASKI INDUSTRIAL AREA', 'WINDSOR HILLS', 'WAKEFIELD',
       'WOODBERRY', 'DOWNTOWN WEST', 'LIBERTY SQUARE',
       'COPPIN HEIGHTS/ASH-CO-EAST', "BUTCHER'S HILL", 'WRENLANE',
       'NEW SOUTHWEST/MOUNT CLARE', 'EAST ARLINGTON', 'RIVERSIDE',
       'MILLHILL', 'RAMBLEWOOD', 'GREEKTOWN', 'PIMLICO GOOD NEIGHBORS',
       'GUILFORD', 'BETTER WAVERLY', 'CANTON INDUSTRIAL AREA',
       'LUCILLE PARK', 'ROLAND PARK', 'OLD GOUCHER', 'EASTWOOD',
       "O'DONNELL HEIGHTS", 'WYNDHURST', 'GWYNNS FALLS/LEAKIN PARK',
       'GWYNNS FALLS', 'BROENING MANOR', 'PENN-FALLSWAY', 'WILHELM PARK',
       'SAINT HELENA', 'LAKE WALKER', 'CAMERON VILLAGE', 'CEDARCROFT',
       'OAKENSHAWE', 'WEST ARLINGTON', 'COLDSPRING',
       'LOWER HERRING RUN PARK', 'STADIUM AREA', 'CALLAWAY-GARRISON',
       'WOODBOURNE-MCCABE', 'DARLEY PARK', 'HIGHLANDTOWN',
       'JOHNS HOPKINS HOMEWOOD', 'OTTERBEIN', 'JOHNSTON SQUARE',
       'LOCUST POINT INDUSTRIAL AREA', 'HERITAGE CROSSING',
       'ORANGEVILLE INDUSTRIAL AREA', 'PARKSIDE',
       'UNIVERSITY OF MARYLAND', 'BARRE CIRCLE', 'MAYFIELD',
       'GREENMOUNT WEST', 'FAIRMONT', 'SOUTH CLIFTON PARK', 'DICKEYVILLE',
       'MORGAN STATE UNIVERSITY', 'MOUNT HOLLY', 'TAYLOR HEIGHTS',
       'EDGEWOOD', 'HERRING RUN PARK', 'PLEASANT VIEW GARDENS',
       'EVERGREEN LAWN', 'ROSEMONT EAST', 'HAWKINS POINT', 'PURNELL',
       'BIDDLE STREET', 'LOWER EDMONDSON VILLAGE', 'LAKE EVESHAM',
       'SABINA-MATTFELDT', 'PORT COVINGTON', 'PATTERSON PARK',
       'MORAVIA-WALTHER', 'FOREST PARK GOLF COURSE', 'LEVINDALE',
       'BOYD-BOOTH', 'TREMONT', 'MORGAN PARK', 'UPLANDS', 'WINCHESTER',
       'KERNEWOOD', 'LOCUST POINT', 'CROSS KEYS',
       'HOLABIRD INDUSTRIAL PARK', 'EVESHAM PARK', 'YORK-HOMELAND',
       'LOYOLA/NOTRE DAME', 'DRUID HILL PARK',
       'STONEWOOD-PENTWOOD-WINSTON', 'OAKLEE', 'WYMAN PARK', 'ROSEBANK',
       'SAINT AGNES', 'CARROLL PARK', 'THE ORCHARDS',
       'SPRING GARDEN INDUSTRIAL AREA', 'BELLONA-GITTINGS',
       'BELAIR-PARKSIDE', 'EVERGREEN', 'CURTIS BAY INDUSTRIAL AREA',
       'BLYTHEWOOD', 'SAINT PAUL', 'GREENMOUNT CEMETERY',
       'MT PLEASANT PARK', 'Jonestown', 'Inner Harbor', 'Frankford',
       'Park Circle', 'Madison-Eastend', 'Sandtown-Winchester',
       'Levindale', 'West Forest Park', 'Central Park Heights', 'Berea',
       'Ashburton', 'Loch Raven', 'Coldstream Homestead Montebello',
       'Cheswolde', 'Brewers Hill', 'Cherry Hill', 'Barclay',
       'Rosemont East', 'Fairfield Area', 'Riverside', 'Penn North',
       'Milton-Montford', 'McElderry Park', 'Cedonia', 'Cross Country',
       'Pulaski Industrial Area', 'Belair-Edison', 'Sharp-Leadenhall',
       'Seton Hill', 'Millhill', 'Canton',
       'Penrose/Fayette Street Outreach', 'Violetville', 'Allendale',
       'Broadway East', 'Lower Edmondson Village', 'Grove Park',
       'Carroll - Camden Industrial Area', 'Westgate', 'Downtown',
       'North Harford Road', 'Wrenlane', 'Better Waverly', 'Fells Point',
       'Ellwood Park/Monument', 'Madison Park', 'Hollins Market',
       'Harlem Park', 'Greenspring', 'Charles Village', 'Morrell Park',
       'Brooklyn', 'Highlandtown', 'Pen Lucy',
       'New Southwest/Mount Clare', 'Stadium Area', 'Patterson Place',
       'Garwyn Oaks', 'Coldspring', 'Otterbein', 'Yale Heights',
       'Reisterstown Station', 'East Baltimore Midway', 'Howard Park',
       'Woodbourne-McCabe', 'Coppin Heights/Ash-Co-East', 'Druid Heights',
       'Kenilworth Park', 'Dolfield', 'Ednor Gardens-Lakeside',
       'Woodmere', 'Medfield', 'Reservoir Hill', 'Oldtown',
       'Mid-Town Belvedere', 'Armistead Gardens', 'Downtown West',
       'Upper Fells Point', 'Federal Hill', 'Mondawmin', 'Gay Street',
       'Glenham-Belhar', 'Pimlico Good Neighbors', 'Curtis Bay',
       'Shipley Hill', 'Westfield', 'Middle Branch/Reedbird Parks',
       'Langston Hughes', 'Walbrook', 'Dunbar-Broadway',
       'Richnor Springs', "Ridgely's Delight", 'Perring Loch', 'Hampden',
       'South Baltimore', 'Cross Keys', 'Johnston Square', 'Roland Park',
       'Harwood', 'Franklintown Road', 'Penn-Fallsway', 'Orangeville',
       'Franklin Square', 'Edmondson Village', 'Westport', 'Lakeland',
       'Morgan Park', 'Rosebank', 'Rosemont', 'Glen', "Butcher's Hill",
       'Glen Oaks', 'Mount Vernon', 'Irvington', 'Cameron Village',
       'Purnell', 'East Arlington', 'Fallstaff', 'Dorchester',
       'Mid-Govans', 'Greektown', 'Easterwood', 'Mount Holly',
       'Concerned Citizens Of Forest Park', 'Parkside', 'Four By Four',
       'Wakefield', 'Ten Hills', 'Lucille Park', 'Saint Paul',
       'Morgan State University', 'Towanda-Grantley', 'Upton', 'Cedmont',
       'Forest Park', 'Oliver', 'Saint Josephs', 'Poppleton',
       'Carrollton Ridge', 'Cylburn', 'Waltherson',
       'Patterson Park Neighborhood', 'Carroll-South Hilton', 'Waverly',
       'Sabina-Mattfeldt', 'Parkview/Woodbrook', 'Medford',
       'North Roland Park/Poplar Hill', 'Bridgeview/Greenlawn',
       'Edgewood', 'Beechfield', 'University Of Maryland', 'Saint Agnes',
       'Pleasant View Gardens', 'South Clifton Park', 'Graceland Park',
       'Hamilton Hills', 'Washington Village/Pigtown',
       'Central Forest Park', 'Bolton Hill', 'Midtown-Edmondson',
       'Broening Manor', 'Spring Garden Industrial Area',
       'Baltimore Highlands', 'Charles North', 'Union Square',
       'Old Goucher', 'Hopkins Bayview', 'Chinquapin Park', 'Parklane',
       'Franklintown', 'Remington', 'Idlewood',
       'Rosemont Homeowners/Tenants', 'Original Northwood',
       'Northwest Community Action', 'Oakenshawe', 'Radnor-Winston',
       'Lauraville', 'Winchester', 'Tuscany-Canterbury', 'Winston-Govans',
       'Wilhelm Park', 'Locust Point', 'Barre Circle', 'Hoes Heights',
       'Middle East', 'Mosher', 'Greenmount West', 'Hanlon-Longwood',
       'Bayview', 'Boyd-Booth', 'Liberty Square', 'Tremont', 'Wyndhurst',
       'Villages Of Homeland', "O'Donnell Heights", 'Beverly Hills',
       'Mount Washington', 'Arlington', 'Biddle Street',
       'Locust Point Industrial Area', 'Windsor Hills', 'West Hills',
       'Little Italy', 'Rognel Heights', 'Woodbourne Heights',
       'Carroll Park', 'Burleith-Leighton', 'Holabird Industrial Park',
       'Moravia-Walther', 'Loyola/Notre Dame', 'West Arlington',
       'Orchard Ridge', 'Guilford', 'Stonewood-Pentwood-Winston',
       'Hillen', 'Callaway-Garrison', 'Mayfield', 'New Northwood',
       'Montebello', 'Wyman Park', 'Lake Walker',
       'Panway/Braddish Avenue', 'Oaklee', 'Saint Helena',
       'Washington Hill', 'Jones Falls Area', 'Heritage Crossing',
       'York-Homeland', 'Canton Industrial Area', 'Gwynns Falls',
       'Ramblewood', 'Arcadia', 'Abell', 'Homeland', 'Taylor Heights',
       'Druid Hill Park', 'Uplands', 'Perkins Homes', 'Woodberry',
       'Overlea', 'Darley Park', 'Hunting Ridge', 'Patterson Park',
       'Kresson', 'Mount Winans', 'Seton Business Park', 'Wilson Park',
       'Kernewood', 'Belvedere', 'Evergreen Lawn', 'Clifton Park',
       'Keswick', 'Fairmont', 'Evesham Park', 'Eastwood',
       'Orangeville Industrial Area', 'Port Covington', 'Dickeyville',
       'Hawkins Point', 'Belair-Parkside', 'Gwynns Falls/Leakin Park',
       'Cedarcroft', 'Lake Evesham', 'Evergreen',
       'Curtis Bay Industrial Area', 'Johns Hopkins Homewood',
       'Mt Pleasant Park', 'The Orchards', 'Forest Park Golf Course',
       'Bellona-Gittings'], dtype=object)

In [246]:
enc = OrdinalEncoder()

In [247]:
print(enc)

OrdinalEncoder()

In [248]:
enc.fit_transform(df[["Neighborhood"]])

array([[157.],
       [339.],
       [183.],
       ...,
       [293.],
       [ 65.],
       [ 65.]])

In [249]:
df[["Neighborhood"]] = enc.fit_transform(df[["Neighborhood"]])

In [250]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,157.0,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,339.0,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT / AGG. ASSAULT
2,2012,12,31,25,WHITE,SOUTHEAST,183.0,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,217.0,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
4,2012,12,31,25,WHITE,SOUTHEAST,247.0,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY

In [251]:
df[["Premise"]] = enc.fit_transform(df[["Premise"]])

In [252]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,157.0,13.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,339.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT / AGG. ASSAULT
2,2012,12,31,25,WHITE,SOUTHEAST,183.0,120.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,217.0,88.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
4,2012,12,31,25,WHITE,SOUTHEAST,247.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY

In [253]:
df["Description"].unique()

array(['LARCENY / BURGLARY / ROBBERY', 'COMMON ASSAULT / AGG. ASSAULT',
       'HOMICIDE / SHOOTING', 'ARSON', 'RAPE'], dtype=object)

In [254]:
label_encoder = LabelEncoder()

In [255]:
print(label_encoder)

LabelEncoder()

In [256]:
df["Description"] = label_encoder.fit_transform(df["Description"])

In [257]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,157.0,13.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,339.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,1
2,2012,12,31,25,WHITE,SOUTHEAST,183.0,120.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,217.0,88.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3
4,2012,12,31,25,WHITE,SOUTHEAST,247.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3

In [258]:
df["Description"].unique()

array([3, 1, 2, 0, 4])

In [259]:
df.to_csv('final_model6.csv', index = True)